version: "3.9"
services:
  orca-nest:
    restart: always
    build: orca-chat-nest
    mem_limit: 512m
    ports:
      - 4444:4444

  orca-quasar:
    restart: always
    build: orca-chat-quasar
    ports:
      - 2895:80
    links:
      - orca-nest
